const userInfo = [
  {
    firstName: "Cody",
    lastName: "Pug",
    email: "codythepug@mail.com",
    password: "123",
    interests: ["sports", "food", "music/arts"],
    borough: "Manhattan",
    isAdmin: "false",
  },
  {
    firstName: "Rosa",
    lastName: "Woahza",
    email: "woahzarosa@abc123.com",
    password: "cre8AnotherHashedPW2",
    interests: ["multicultural", "seniors", "health"],
    borough: "Brooklyn",
    isAdmin: "false",
  },
  {
    firstName: "Martin",
    lastName: "Price",
    email: "mprice@pocketnyc.org",
    password: "HashDisTwo123#",
    interests: ["finance", "education", "outdoors"],
    borough: "Queens",
    isAdmin: "true",
  },
  {
    firstName: "Jazmin",
    lastName: "McDowell",
    email: "jmdowell2@totallyrealwebsite.com",
    password: "LolHashThis2",
    interests: ["holidays", "disability services", "clothes"],
    borough: "Bronx",
    isAdmin: "false",
  },
  {
    firstName: "Cecily",
    lastName: "Rodriguez",
    email: "crod@pocketnyc.gov",
    password: "CRocHashPW",
    interests: ["clothes", "city services", "employment"],
    borough: "Staten Island",
    isAdmin: "true",
  },
  {
    firstName: "Syed",
    lastName: "Rahman",
    email: "syedsyed@mail.com",
    password: "BcryptHashOrSumn",
    interests: ["music/arts", "seniors", "food"],
    borough: "Queens",
    isAdmin: "false",
  },
  {
    firstName: "George",
    lastName: "Lopez",
    email: "glopez@nickatnite.com",
    password: "Nick@Nite123",
    interests: ["education", "family-friendly", "city services"],
    borough: "Brooklyn",
    isAdmin: "true",
  },
  {
    firstName: "Penny",
    lastName: "Proud",
    email: "pennystwocents@mail.com",
    password: "aPenny4UrThoughtz98",
    interests: ["holidays", "multicultural", "health"],
    borough: "Bronx",
    isAdmin: "false",
  },
  {
    firstName: "Noorinna",
    lastName: "Cythiana",
    email: "realemail@email.com",
    password: "iPutOurNames2GetHer1!",
    interests: ["finance", "food", "family-friendly"],
    borough: "Staten Island",
    isAdmin: "false",
  },
  {
    firstName: "Gabriel",
    lastName: "Stone",
    email: "gstone@manifest.org",
    password: "Fl!ght828",
    interests: ["clothes", "outdoors", "sports"],
    borough: "Manhattan",
    isAdmin: "false",
  },
];

module.exports = { userInfo };
